# Generated by Django 5.1.7 on 2025-04-01 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_inventoryitem_alter_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='food_item',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='myapp.inventoryitem'),
        ),
    ]
