# Generated by Django 5.1.7 on 2025-04-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_myorder_food_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='ordered_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
